### ISSUE TITLE
【Bug】编译出现问题 go: no Go source files

### ISSUE THREAD

**Issue by tzf1003** [Ed1s0nZ/externalC2Client#2]
编译出现问题go: no Go source files
![image](https://github.com/Ed1s0nZ/externalC2Client/assets/46259700/a1b458e2-685f-4b05-b38c-2e140487d2ac)

**Comment by tzf1003** [comment]
已经解决，需要安装mingw64环境，安装后配置环境变量为\mingw64\bin，即可编译

**Comment by Ed1s0nZ** [comment]
已更新readme。
